### ISSUE TITLE
IOS like swipe actions

### ISSUE THREAD

**Issue by ansarizafar** [expandjs/mat-item#1]
Is it possible to implement IOS like swipe actions with mat-item? If yes then could you please share an example.

**Comment by Pupix** [comment]
Yes, you can use [`iron-swipeable-container`](https://elements.polymer-project.org/elements/iron-swipeable-container) like so:

```
<iron-swipeable-container>
    <mat-item label="hello" description="world"></mat-item>
    <mat-item label="hello" description="world"></mat-item>
    <mat-item label="hello" description="world"></mat-item>
</iron-swipeable-container>
```

**Comment by ansarizafar** [comment]
@Pupix I don't want to remove the item. I would like to implement swipe actions like this element [Swipe action element](https://customelements.io/vguillou/swipe-action/). Expandjs looks amazing but I have not seen activity since last December. Is this project dead?

**Comment by Pupix** [comment]
Oh, you meant `leave-behinds` not just `swipe`. Can't you just use that element and wrap the `mat-item` with it? I see this is what he does in the demo [here](https://github.com/vguillou/swipe-action/blob/master/demo/index.html#L166)

Thanks! The project is not dead, we've just been busy testing it in a more serious (enterprise) environment. While doing so we are hotfixing and moving parts around very often, and we felt it would be too cumbersome to constantly update the public git repos and potentially break people's stuff.

**Comment by ansarizafar** [comment]
I have tested that element. It has several issues and don't work as expected. I am starting a new project and I want to use elementjs. If its possible, can I have access to the latest version.

**Comment by Pupix** [comment]
You should post on their repository if you have issues with their component, so they can fix it.
